sudo: false
language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test           # ppa:ubuntu-toolchain-r/test
    packages:
      - gcc-5
      - g++-5
      - wget

install:
  # Use GCC 5.
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  # Download CMake binary because those available in PPAs either don't support
  # xz downloads or don't support HTTPS.
  - wget https://cmake.org/files/v3.6/cmake-3.6.2-Linux-x86_64.tar.gz
  - tar -xf cmake-3.6.2-Linux-x86_64.tar.gz

before_script:
  # Move into the cloned LOOT repo build path.
  - mkdir build && cd build
  # Link dynamically to the C++ standard library runtime.
  - ../cmake-3.6.2-Linux-x86_64/bin/cmake ..

script:
  - make all
  - python -m unittest test

after_success:
  - ../cmake-3.6.2-Linux-x86_64/bin/cpack -C Release
  - cd $TRAVIS_BUILD_DIR
  # Need to replace the Bintray config files' version placeholders.
  - VERSION=$(ls build/package/loot_api_python-*.tar.xz | sed 's/build\/package\/loot_api_python-//;s/-Linux.tar.xz//;')
  - sed -i "s/REPLACE_THIS_VERSION/${VERSION}/" scripts/travis/loot-api.bintray.json

deploy:
  - provider: bintray
    file: scripts/travis/loot-api.bintray.json
    user: wrinklyninja
    key:
      secure: "qIZDcrbv3ELv/rHqryFT/cHXIUhQPMPvgjcKUGhIa+9oHOF6M2Y26qy5CTERb1CWePY/EiPC58F9Z4yTFA+M5b22dMdRcSXkdd7wxdeqxfZP4RzTa0hbXZpAl2deOxLhecUtV+L41frHTP0ZOyr+k6T9OWW03OK1gioSWJwx77r1rIR8x/Q4DXhFDntPi/97AOZhWDg0aht3NoS553oXz0l4rXNQbbL2aDPGAoZOWHPAQhK/mmFPxFILJpUv2FBE+3fJd1u5oKh87KRbWatJaAz+1F1R4+bxwV2heqXkvkEW7+xirEUxtohbFMBG7tSFqa4purSBFs1IEeXFer/mhQZVbx7+/95AY0N5XJeLgy+OPPBb53Ez18sZpUckW8zxlKB2e1Y3mgLrd5gtlLwuO3WrjR1DE7eQ5xCPRBuJzSTYUX4gOmDrkEpmo+RaFaJI2Qo9ZktApV0oP9U9D5fNNEcvUJlIfqgVPV5n6mCg6PrY08rg4eO3icw6dEgh7vcVhupZ26i43U3Mhs3z2llh9azOZqoHoaEjSCXQlcixCDIkW6HBsHqkfBS6rm31ojkrJNTUHF/AqJljb6c0nCkh2T2N2TyDJCWUnR6+QmGryKuTtL2E2AEIqAiDSh7S8xcdJ8qYBWWva/a3YtqIryNyMBnHro+t30a6qvV7XL5PTDg="
    skip_cleanup: true
    on:
      all_branches: true
