os: Visual Studio 2017

version: "{build}-{branch}"

configuration: RelWithDebInfo

platform:
  - Win32
  - x64

environment:
  bintray_auth_token:
    secure: PgsEA6TjHVf718zMnK7J/fT1hUAVNKBeWhpYgYaeCyeZk37VT4Ics6j7+B7ElLEr
  github_auth_token:
    secure: yDqT5l/e5MntbW99V6+MHlfFgNv+UIogFfeyUVqtFk5lFRB/dAraLLwKCLl6y+DH

  matrix:
    - PYTHON_VERSION: 2.7
    - PYTHON_VERSION: 3.7

install:
  - ps: (New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/Ortham/ci-scripts/2.0.0/delete_old_bintray_versions.py', "$env:APPVEYOR_BUILD_FOLDER\delete_old_bintray_versions.py")
  - ps: (New-Object Net.WebClient).DownloadFile('https://github.com/WrinklyNinja/testing-plugins/archive/1.4.1.zip', "$PWD/1.4.1.zip")
  - 7z x 1.4.1.zip
  - mv testing-plugins-1.4.1 testing-plugins

before_build:
  - ps: $env:PYTHON_DIRECTORY_VERSION=$env:PYTHON_VERSION.Replace(".", "")
  - cd %APPVEYOR_BUILD_FOLDER%
  - ps: mkdir build
  - cd build
  - ps: |
      if ($env:PLATFORM -eq 'Win32') {
        cmake .. -G "Visual Studio 15 2017" -DPYTHON_EXECUTABLE="C:\Python${env:PYTHON_DIRECTORY_VERSION}\python.exe"
      } else {
        cmake .. -G "Visual Studio 15 2017" -A x64 -DPYTHON_EXECUTABLE="C:\Python${env:PYTHON_DIRECTORY_VERSION}-x64\python.exe"
      }

build:
  verbosity: minimal
  project: 'c:\projects\libloot-python\build\libloot-python.sln'

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%\build
  - ctest -C %CONFIGURATION%

after_test:
  - cd %APPVEYOR_BUILD_FOLDER%\build
  - cpack -C %CONFIGURATION%
  - ps: $env:GIT_DESCRIBE = ((git describe --tags --long --always) | Out-String) -replace "`n|`r", ""
  - ps: $env:PACKAGE_VERSION = $env:GIT_DESCRIBE + "_" + ($env:APPVEYOR_REPO_BRANCH.replace("/", "-"))
  - ps: $env:ARCHITECTURE = $env:PLATFORM.substring($env:PLATFORM.length - 2)

artifacts:
  - path: build\package\libloot-python-$(PACKAGE_VERSION)-python$(PYTHON_VERSION)-win$(ARCHITECTURE).zip
    name: libloot-python

deploy:
  - provider: BinTray
    username: wrinklyninja
    api_key:
      secure: PgsEA6TjHVf718zMnK7J/fT1hUAVNKBeWhpYgYaeCyeZk37VT4Ics6j7+B7ElLEr
    subject: loot
    repo: snapshots
    package: libloot-python
    version: $(PACKAGE_VERSION)
    publish: true
    artifact: libloot-python

  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: libloot-python v$(APPVEYOR_REPO_TAG_NAME)
    description: |
      Requires Windows 7 or later and the [MSVC 2017 x86 redistributable](https://download.visualstudio.microsoft.com/download/pr/749aa419-f9e4-4578-a417-a43786af205e/d59197078cc425377be301faba7dd87a/vc_redist.x86.exe), and [7-Zip](http://www.7-zip.org/) to extract the archive.
    auth_token:
      secure: yDqT5l/e5MntbW99V6+MHlfFgNv+UIogFfeyUVqtFk5lFRB/dAraLLwKCLl6y+DH
    artifact: libloot-python
    draft: false
    on:
      appveyor_repo_tag: true

on_success:
  - ps: python "$env:APPVEYOR_BUILD_FOLDER\delete_old_bintray_versions.py" -g loot/libloot-python -b loot/snapshots/libloot-python -u wrinklyninja -k $env:bintray_auth_token -t $env:github_auth_token -n 30
