os: Visual Studio 2015

version: "{build}-{branch}"

configuration: Release

before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - ps: mkdir build
  - cd build
  - cmake .. -G "Visual Studio 14 2015"

build:
  verbosity: minimal
  project: 'c:\projects\loot-api-python\build\loot_api_python.sln'

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%\build
  - ctest -C Release

after_test:
  - cpack
  # AppVeyor checks out a specific commit, but that means the archive script
  # can't tell which branch it's on, so rename the 7z archives.
  - ps: $env:GIT_DESCRIBE = ((git describe --tags --long --always) | Out-String) -replace "`n|`r", ""

artifacts:
  - path: build\package\loot_api_python-$(GIT_DESCRIBE)-win32.7z
    name: loot_api_python

deploy:
  - provider: BinTray
    username: wrinklyninja
    api_key:
      secure: u234T2688DZmz4JH5+0iAHcUcL2fEIGculb8655bn4B1q7GckhplsitzgEbv3NFc
    subject: wrinklyninja
    repo: loot
    package: loot-api-python
    version: $(GIT_DESCRIBE)_$(APPVEYOR_REPO_BRANCH)
    publish: true
    artifact: loot_api_python
