os: Visual Studio 2015

version: "{build}-{branch}"

configuration: Release

environment:
  bintray_auth_token:
    secure: fBQJmUDK/EgEUWjjbo6bWcitczeFTJZT4OZ3ZZ4FoUT6soBsTWPQJnr8YEVMFhGP

install:
  - ps: (New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/WrinklyNinja/ci-scripts/1.1.0/delete_old_bintray_versions.py', "$env:APPVEYOR_BUILD_FOLDER\delete_old_bintray_versions.py")

before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - ps: mkdir build
  - cd build
  - cmake .. -G "Visual Studio 14 2015"

build:
  verbosity: minimal
  project: 'c:\projects\loot-api-python\build\loot_api_python.sln'

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%\build\Release
  - python -m unittest test

after_test:
  - cd %APPVEYOR_BUILD_FOLDER%\build
  - cpack
  # AppVeyor checks out a specific commit, but that means the archive script
  # can't tell which branch it's on, so rename the 7z archives.
  - ps: $env:GIT_DESCRIBE = ((git describe --tags --long --always) | Out-String) -replace "`n|`r", ""

artifacts:
  - path: build\package\loot_api_python-$(GIT_DESCRIBE)_$(APPVEYOR_REPO_BRANCH)-win32.7z
    name: loot_api_python

deploy:
  - provider: BinTray
    username: wrinklyninja
    api_key:
      secure: fBQJmUDK/EgEUWjjbo6bWcitczeFTJZT4OZ3ZZ4FoUT6soBsTWPQJnr8YEVMFhGP
    subject: wrinklyninja
    repo: loot
    package: loot-api-python
    version: $(GIT_DESCRIBE)_$(APPVEYOR_REPO_BRANCH)
    publish: true
    artifact: loot_api_python

on_success:
  - ps: python "$env:APPVEYOR_BUILD_FOLDER\delete_old_bintray_versions.py" -o loot -g loot-api-python -u wrinklyninja -b loot -p loot-api-python -t $env:bintray_auth_token -n 30
