os: Visual Studio 2015

version: "{build}-{branch}"

configuration: RelWithDebInfo

environment:
  bintray_auth_token:
    secure: fBQJmUDK/EgEUWjjbo6bWcitczeFTJZT4OZ3ZZ4FoUT6soBsTWPQJnr8YEVMFhGP

install:
  - ps: (New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/WrinklyNinja/ci-scripts/1.1.0/delete_old_bintray_versions.py', "$env:APPVEYOR_BUILD_FOLDER\delete_old_bintray_versions.py")

before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - ps: mkdir build
  - cd build
  - cmake .. -G "Visual Studio 14 2015"

build:
  verbosity: minimal
  project: 'c:\projects\loot-api-python\build\loot_api_python.sln'

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%\build\%CONFIGURATION%
  - python -m unittest test

after_test:
  - cd %APPVEYOR_BUILD_FOLDER%\build
  - cpack -C %CONFIGURATION%
  # AppVeyor checks out a specific commit, but that means the archive script
  # can't tell which branch it's on, so rename the 7z archives.
  - ps: $env:GIT_DESCRIBE = ((git describe --tags --long --always) | Out-String) -replace "`n|`r", ""

artifacts:
  - path: build\package\loot_api_python-$(GIT_DESCRIBE)_$(APPVEYOR_REPO_BRANCH)-win32.7z
    name: loot_api_python

deploy:
  - provider: BinTray
    username: wrinklyninja
    api_key:
      secure: fBQJmUDK/EgEUWjjbo6bWcitczeFTJZT4OZ3ZZ4FoUT6soBsTWPQJnr8YEVMFhGP
    subject: loot
    repo: snapshots
    package: loot-api-python
    version: $(GIT_DESCRIBE)_$(APPVEYOR_REPO_BRANCH)
    publish: true
    artifact: loot_api_python

  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: LOOT API Python Module v$(APPVEYOR_REPO_TAG_NAME)
    description: |
      Requires Windows 7 or later and the [MSVC 2015 x86 redistributable](https://download.microsoft.com/download/6/A/A/6AA4EDFF-645B-48C5-81CC-ED5963AEAD48/vc_redist.x86.exe), and [7-Zip](http://www.7-zip.org/) to extract the archive.
    auth_token:
      secure: V1GojGQfrAiQtUWtNNXfm3samiH+1yNF5UYhkn8B8mbif20IGTGWNlBS9E4S0SUC
    artifact: loot_api_python
    draft: false
    on:
      appveyor_repo_tag: true

on_success:
  - ps: python "$env:APPVEYOR_BUILD_FOLDER\delete_old_bintray_versions.py" -o loot -g loot-api-python -u loot -b snapshots -p loot-api-python -t $env:bintray_auth_token -n 30
